TechsCode-Team/PluginPermissions

Permissions/Database.updb

Attempt 2 on the ultra regions update

Updated Ultra Regions perms

---

Permissions/Database.updb

update on UPun permissions

---

Permissions/Database.updb

Add Permission to the data base for the plugin Epic Levels
Plugin link : https://songoda.com/marketplace/product/epiclevels-gain-levels-by-fighting.44
Plugin perms link : https://wiki.songoda.com/Epic_Levels
Premium plugin :  name: EpicLevels
description: EpicLevels
version: maven-version-number
main: com.songoda.epiclevels.EpicLevels
author: songoda
softdepend: [Vault, PlaceholderAPI]
commands:
EpicLevels:
description: View information on this plugin.
default: true
aliases: [el, levels, level]
usage: /levels
- fixed ...
- the implementation should be reworked
- added logs for ...

Add Perms for EpicLevels

---

Permissions/Database.updb

Hello i do little Pull for adding the permission of Deluxe Void World to the data base.
Plugin and perms link :  https://songoda.com/marketplace/product/deluxe-void-world-188-116-fall-into-the-void-with-effects-unique-to-this-plugin.532
Permium Plugin : #                                                           Developed by Ruben_Artz
#
name: DeluxeVoidWorld
main: ruben_artz.bukkit.World.VOMain
version: 1.3.0
author: Ruben_Artz
api-version: 1.15
softdepend:
- PlaceholderAPI
website: https://stn-studios.com/
description: Incredible plugin to send your players when they fall into the void!
commands:
deluxevoidworld:
aliases: [dew]
empty:
aliases:
- void
- fixed ...
- the implementation should be reworked
- added logs for ...

Add perms for DeluxeVoidWorld

---

Permissions/Database.updb

Hello i have see EpicFarming don't have all the perms if you can add that to the data base that cool ^^
Plugin Link : https://songoda.com/marketplace/product/epicfarming-ultimate-minecraft-farming.21
Permission Link :  https://wiki.songoda.com/Epic_Farming
Premium Plugin :  name: EpicFarming
description: EpicFarming
main: com.songoda.epicfarming.EpicFarming
version: 3.1.2
softdepend: [FabledSkyBlock, Arconix, SkyBlock, Towny, RedProtect, Kingdoms, PlotSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions,  
PlaceholderAPI, Vault, PlayerPoints, Reserve, StackMob, UltimateStacker, WildStacker]
author: Songoda
commands:
EFA:
description: View information on this plugin.
default: true
aliases: [EpicFarming]
usage: /efa
- fixed ...
- the …

Add perms for EpicFarming

---

Permissions/Database.updb

Hello i do little Pull to add permission of Play Time to the database.
Plugin and Perms Link : https://songoda.com/marketplace/product/playtime-playtime.486
- fixed ...
- the implementation should be reworked
- added logs for ...

Add perms for PlayTime

---

Permissions/Database.updb

**Plugin Added:** [FateUHC](https://www.mc-market.org/resources/9081/)
**Permissions:** [Wiki](https://fateuhc.bghddevelopment.com/commands-and-permissions)
**plugin.yml**
```
name: FateUHC
version: 3.100
description: UHC - Ultra Hardcore plugin created by BGHDDevelopment
website: bghddevelopment.com
main: net.fateuhc.plugin.UHC
authors:
- 'BGHDDevelopment'
- 'Noodles_YT'
softdepend:
- PlaceholderAPI
- BossBarAPI
- AdvancedBan
- LiteBans
- AquaCore
- HologramAPI
- NickAPI
- Vault
- Mizu
- Root
- Neutron
- mCore
- Chronium
- HestiaCore
- nCore
- Stark
- qUtilities
- Galaxy
- Zoom
- tModsuite
- AquaCore
- LuckPerms
- Ocean
commands:
wborder:
description: Primary command for WorldBorder. Shaded and modified by FateUHC.
aliases: [worldborder, wb]
```

FateUHC added.

---

Permissions/Database.updb

- fixed ...
- the implementation should be reworked
- added logs for ...

Added CanonHealth

---

Permissions/Database.updb

plugin link: https://www.spigotmc.org/resources/sell-wand.87014/
perms link: https://www.spigotmc.org/resources/sell-wand.87014/
plugin.yml
name: Sellwand
version: ${project.version}
main: me.zachary.sellwand.Sellwand
authors: [ Zach_FR ]
softdepend: [ ShopGUIPlus, HolographicDisplays, zShop, Vault, CMI, QuantumShop, BlockLocker, EconomyShopGUI, WorldGuard, WorldEdit ]
description: Sell wand plugin

Added perms for Sell wand

---

Permissions/Database.updb

Attempt 2 of adding the AACAdditionPRO permissions

Added AACAdditionPRO permissions

---

Permissions/Database.updb

Added the new perms of ultra regions

Updated ultra regions permissions

---

Permissions/Database.updb

**Plugin Added:** [FateHubCore](https://www.mc-market.org/resources/9350/)
**Permissions:** [Wiki](https://fatehub.bghddevelopment.com/commands-and-permissions)
**plugin.yml**
```
name: FateHubCore
version: 2.1.17
description: FateHub core is a plugin that makes it easier for players to have a better and more accessible way of entering the server, from choosing server to play, good looks to fun. All in one plugin.
website: https://www.mc-market.org/resources/9350/
author: BGHDDevelopment
main: net.fatehub.plugin.FateHub
softdepend:
- PlaceholderAPI
- MVdWPlaceholderAPI
- AquaCore
- LuckPerms
- ProtocolLib
- ProtocolSupport
- ViaVersion
- Portal
- Vault
- Mizu
- Root
- Neutron
- mCore
- Chronium
- HestiaCore
- nCore
- Stark
- qUtilities
- Galaxy
- Zoom
- tModsuite
- Ocean
- Oxygen …
```

Added FateHubCore.

---

Permissions/Database.updb

Added all the ultra economy perms

---

Permissions/Database.updb

Plugin: https://www.spigotmc.org/resources/gamemode-change.42765/
Permissions: https://www.spigotmc.org/resources/gamemode-change.42765/

Added Gamemode Change.

---

Permissions/Database.updb

Link to plugin page: https://www.spigotmc.org/resources/xprotect-the-best-protection-plugin-stops-bots-attacks-vpns-more-mysql-1-8-1-16.67863/
Link to permissions page: https://github.com/LagBug/XProtect/wiki/Commands-&-Permissions
Below is the plugin.yml;
```
main: me.lagbug.xprotect.spigot.XProtect
name: XProtect
version: 2.8.1
description: An advanced plugin to separate bots from real players.
author: LagBug
website: https://www.spigotmc.org/resources/67863/
softdepend: [AuthMe, ProtocolLib]
commands:
protect:
aliases: [xprotect, protector, protection, xprotection, prot, xprot, p, manager, servermanager, admingui, admin, captcha, captchax]
description: The main command for this plugin.
```

Added XProtect

---

Permissions/Database.updb

**Plugin Added:** [FateMeetup](https://www.mc-market.org/resources/9082/)
**Permissions:** [Wiki](https://fatemeetup.bghddevelopment.com/commands-and-permissions)
**plugin.yml**
```
name: FateMeetup
version: 2.35
author: BGHDDevelopment
main: net.noodles.meetup.Fate
website: https://bghddevelopment.com
description: FateMeetup by BGHDDevelopment.
softdepend:
- WorldBorder
```

FateMeetup Added.

---

Permissions/Database.updb

1 permissions is wrong I have changed it to the correct one 
UltraRegions+ultraregions.admin.region.bypass+Allows the player to bypass the regions default gamemode. needed to be UltraRegions+ultraregions.gamemode.region.bypass+Allows the player to bypass the regions default gamemode.

Permission update on UR

---

Permissions/Database.updb

- added permissions for UltraEditor commands

Added permissions for UltraEditor

---

Permissions/Database.updb

Plugin page: https://www.spigotmc.org/resources/economyshopgui.69927/
Permission page: https://gpplugins.gitbook.io/economyshopgui/basics/permission
plugin.yml
```name: EconomyShopGUI
version: 3.1.3
main: me.gypopo.economyshopgui.EconomyShopGUI
authors: [Gypopo]
description: This is a simple to use server GUI shop plugin.
softdepend:
- Vault
- SilkSpawners
- WildStacker
commands:
shop:
aliases: shop
description: Opens the server shop.
sreload:
description: Reloads the plugin.
sellall:
aliases: sellall
description: Sells all current items in the inventory.
editshop:
description: Add/remove items from the shop with a command ingame.
aliases: [editshop additem, editshop edititem, editshop deleteitem, editshop addhanditem]
permissions:
EconomyShopGUI.shop:
default: true …
```

Added EconomyShopGUI plugin

---

Permissions/Database.updb

Plugin & Permission Page: https://www.spigotmc.org/resources/bkteleport-essentialsx-add-on.82198/
Plugin.yml
```
name: BkTeleport
version: 2.7.5
main: me.bkrmt.bkteleport.BkTeleport
authors: [Bkr__]
description: 'Replacement for essentials teleport'
```

Added BKTeleport (EssentialsX Add-On)

---

Permissions/Database.updb

Plugin page & Permissions: https://www.spigotmc.org/resources/epiccraftingsplus-fully-configurable-crafts-1-8-1-16.39967/
plugin.yml
```
main: ecp.ajneb97.EpicCraftingsPlus
version: 6.5.2
name: EpicCraftingsPlus
softdepend: [Jobs,Vault,BattleLevels,SkillAPI,TokenEnchant,PlaceholderAPI]
author: Ajneb97
commands:
ecraft:
description: Main Command of EpicCraftingsPlus
permission: ecraft.command.ecraft
permission-message: "You do not have permission!"
permissions:
ecraft.command.ecraft:
default: true
```

Added EpicCraftingsPlus

---

Permissions/Database.updb

Plugin & Permission Page: [UltraSkyWars](https://www.spigotmc.org/resources/ultra-skywars-cubelets-mobfriends-parties-perks-soulwell-challenges-votes-custom-chest.84497/)
plugin.yml
```
name: UltraSkyWars
main: io.github.Leonardo0013YT.UltraSkyWars.UltraSkyWars
version: 8.1.0
author: Leonardo0013YT
load: POSTWORLD
softdepend:
- AnimatedNames
- WorldEdit
- FastAsyncWorldEdit
- PlaceholderAPI
- PlayerPoints
- Vault
- Coins
- Holograms
- HolographicDisplays
- Parties
- TAB
- NametagEdit
- PartyAndFriends
- MVdWPlaceholderAPI
- LeaderHeads
- TrHologram
commands:
sw:
aliases: [ skywars, swars, skyw ]
swp:
aliases: [ swparty ]
party:
aliases: [ p ]
swi:
aliases: [ switems ]
leave:
aliases: [ quit ]
```

Added UltraSkyWars

---

Permissions/Database.updb

Waveguard Anti VPN/Proxy/Bot and Crash plugin
- Added Permissions from WaveGuard
- Link to the Plugin >> https://www.mc-market.org/resources/20303/
- 
[plugin.txt](https://github.com/TechsCode-Team/PluginPermissions/files/6772733/plugin.txt)
[permissions.txt](https://github.com/TechsCode-Team/PluginPermissions/files/6772734/permissions.txt)
[bungee.txt](https://github.com/TechsCode-Team/PluginPermissions/files/6772735/bungee.txt)

Added WaveGuard

---

Permissions/Database.updb

**Plugin Name:** [BetterDrops](https://www.spigotmc.org/resources/betterdrops.7497/)
**Permissions Page:** https://www.spigotmc.org/resources/betterdrops.7497/ (further down the page)
**plugin.yml**
```yml
name: BetterDrops
author: Ruan
version: '2.15.1'
main: betterdrops.BetterDrops
description: '3D drops with customizable nametags and positions.'
website: https://www.spigotmc.org/resources/betterdrops.7497/
depend: [ProtocolLib]
softdepend: [BetterDeaths]
api-version: "1.13"
permissions:
betterdrops.reload:
default: op
betterdrops.toggle-nametags:
default: true
betterdrops.toggle:
default: true
commands:
betterdrops:
description: BetterDrops commands.
usage: /<command> toggle|toggle-nametags|reload
aliases: [drops]
```

Add BetterDrops

---

Permissions/Database.updb

**Plugin Name:** [UltraStaffChat](https://www.spigotmc.org/resources/68956/)
**Permissions Page:** https://docs.hypera.dev/en/docs/ultrastaffchat-bungeecord
**plugin.yml**
[Original](https://github.com/HyperaOfficial/UltraStaffChat/blob/main/src/main/resources/bungee.yml)
```
name: UltraStaffChat
version: ${project.version}
author: "Joshua S, Christian F, SLLCoding, Hunter Y"
main: dev.hypera.ultrastaffchat.UltraStaffChat
description: A 100% Customizable StaffChat Plugin for BungeeCord!
```
Added:
- staffchat.talk
- staffchat.read
- staffchat.toggle
- staffchat.mute
- staffchat.globalmute
- staffchat.mutebypass
- staffchat.list
- staffchat.staff
- staffchat.afk
- staffchat.join
- staffchat.switch
- staffchat.leave
- ultrastaffchat.reload
- ultrastaffchat.update

Add UltraStaffChat permissions

---

Permissions/Database.updb

**Plugin Name:** [BlockLocker](https://www.spigotmc.org/resources/blocklocker.3268/)
**Permissions Page:** *https://www.spigotmc.org/resources/blocklocker.3268/* (the permissions are near the middle of the listing)
**plugin.yml**
```yaml
name: BlockLocker
version: "1.10.1"
main: nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl
author: Rutger Kok
load: startup
api-version: 1.14
softdepend: [Guilds, Factions, mcMMO, Towny]
permissions:
blocklocker.protect:
description: "Protect containers and doors."
default: true
blocklocker.bypass:
description: "Bypass someone else's protection."
default: op
blocklocker.reload:
description: "Reload the plugin using /blocklocker reload."
default: op
blocklocker.wilderness:
description: "Place chests in the wilderness (outside of Towny claims)"
default: …
```

Add BlockLocker (Lockette/LockettePro alternative)

---

Permissions/Database.updb

**Plugin Name:** [SuperVanish](https://www.spigotmc.org/resources/supervanish-be-invisible.1331/)
**Permissions Page:** *https://www.spigotmc.org/resources/supervanish-be-invisible.1331/* (permissions are on same page)
Note: changes were based off [SuperVanish's plugin.yml](https://github.com/LeonMangler/SuperVanish/blob/master/src/main/resources/plugin.yml) and its permissions page
Added:
`sv.toggleitems` - toggle picking up items off floor
`sv.joinvanished` - You always join vanished (must be enabled in config).
`sv.damage` - Bypass permisison for hitting entities prevention
`sv.stacktrace` - Print stacktrace for debugging
`sv.notify` - Receive update notifications, if there is a new version to download
`sv.notoggle` - Other players cannot hide/show you if you're online …

Update SuperVanish perms to latest (6.2.6)

---

Permissions/Database.updb

Plugin website: https://ultrapunishments.com/
Plugin permissions website: https://ultrapunishments.com/wiki/overview/permissions
Plugin.yml: [plugin.zip](https://github.com/TechsCode-Team/PluginPermissions/files/11078291/plugin.zip)
_(Had to put the plugin.yml into a zip archive because github wouldn't let me upload it if it was only a .yml file)_
Changed: **I changed order of how the UltraPunishments permissions were arranged, so it can be identical to how it is on the plugin wiki.**

UltraPunishments - Order change
